# Generated by Django 2.0.7 on 2018-07-15 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yohbiteapp', '0006_auto_20180715_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yohbiteapp.Driver'),
        ),
    ]
