# Generated by Django 2.2 on 2019-04-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yohbiteapp', '0009_auto_20190412_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='state',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='state',
            new_name='district',
        ),
    ]
