# Generated by Django 2.2 on 2019-04-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yohbiteapp', '0010_auto_20190412_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='yohbiteapp.District'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='yohbiteapp.Location'),
        ),
    ]
