# Generated by Django 2.2 on 2019-04-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yohbiteapp', '0011_auto_20190412_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_index',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
